# Generated by Django 4.0.3 on 2023-02-03 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
        ('tvshows', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvshow',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pages.category'),
        ),
        migrations.AlterField(
            model_name='tvshow',
            name='release_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pages.release_year'),
        ),
    ]
