# Generated by Django 4.0.3 on 2023-02-12 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tvshows', '0003_tvshow_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='tvshow_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tvshows.tvshow'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user_nam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tvshow_comment', to=settings.AUTH_USER_MODEL),
        ),
    ]
