# Generated by Django 4.0.3 on 2023-02-12 17:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_release_year_options'),
        ('tvshows', '0004_alter_comment_tvshow_name_alter_comment_user_nam'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('season_number', models.IntegerField()),
                ('watch_url', models.TextField()),
                ('publish_date', models.DateTimeField(default=datetime.datetime.now)),
                ('release_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tvshow_parts', to='pages.release_year')),
            ],
        ),
    ]
