# Generated by Django 4.0.3 on 2023-02-12 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tvshows', '0006_part_poster_alter_tvshow_poster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tvshow',
            name='download_url',
        ),
        migrations.RemoveField(
            model_name='tvshow',
            name='video_url',
        ),
    ]
