# Generated by Django 4.0.3 on 2023-02-12 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tvshows', '0008_tvshow_parts_tvshow_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tvshow',
            old_name='season',
            new_name='number_Of_seasons',
        ),
    ]
