# Generated by Django 4.0.3 on 2023-02-13 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvshows', '0010_alter_tvshow_is_trend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvshow',
            name='parts',
            field=models.ManyToManyField(null=True, to='tvshows.part'),
        ),
        migrations.AlterField(
            model_name='tvshow',
            name='tags',
            field=models.ManyToManyField(null=True, to='tvshows.tag'),
        ),
    ]
