# Generated by Django 4.0.3 on 2023-02-13 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cast_and_crew', '0003_delete_category_delete_release_year'),
        ('tvshows', '0014_alter_part_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvshow',
            name='casts',
            field=models.ManyToManyField(blank=True, to='cast_and_crew.cast'),
        ),
        migrations.AlterField(
            model_name='tvshow',
            name='director',
            field=models.ManyToManyField(blank=True, to='cast_and_crew.director'),
        ),
        migrations.AlterField(
            model_name='tvshow',
            name='parts',
            field=models.ManyToManyField(blank=True, to='tvshows.part'),
        ),
        migrations.AlterField(
            model_name='tvshow',
            name='tags',
            field=models.ManyToManyField(blank=True, to='tvshows.tag'),
        ),
        migrations.AlterField(
            model_name='tvshow',
            name='writer',
            field=models.ManyToManyField(blank=True, to='cast_and_crew.writer'),
        ),
    ]
