# Generated by Django 4.0.3 on 2023-02-13 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tvshows', '0015_alter_tvshow_casts_alter_tvshow_director_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='part',
            options={'ordering': ['-season_number']},
        ),
        migrations.RemoveField(
            model_name='tvshow',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
