# Generated by Django 4.0.3 on 2023-02-14 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tvshows', '0018_remove_tvshow_parts_tvshow_watch_url_delete_part'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tvshow',
            old_name='number_Of_seasons',
            new_name='season',
        ),
    ]
