# Generated by Django 4.0.3 on 2023-09-03 14:53

from django.db import migrations
from django.utils.text import slugify

def update_existing_objects(apps,schema_editor):

    Tvshow = apps.get_model('tvshows','Tvshow')
    

    for tvshow in Tvshow.objects.all():
        tvshow.slug = slugify(tvshow.name + ' ' + str(tvshow.season) )
        tvshow.save()

class Migration(migrations.Migration):

    dependencies = [
        ('tvshows', '0028_alter_tvshow_slug'),
    ]

    operations = [
        migrations.RunPython(update_existing_objects)
    ]
