# Generated by Django 4.0.3 on 2023-05-29 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='sequrty_question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('name_ar', models.TextField()),
            ],
        ),
    ]
