# Generated by Django 4.0.3 on 2023-05-29 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_sequrty_question'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sequrty_question',
        ),
    ]
