"""
Django settings for movflex project.

Generated by 'django-admin startproject' using Django 4.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-d91g!-cb(waws7bixv%zzaq7dzbt3f$kfj&!6=i$-9asjl&s8s'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*'] 


# Application definition

INSTALLED_APPS = [
    #apps
    'top_rank.apps.TopRankConfig',
    'cast_and_crew.apps.CastAndCrewConfig',
    'tvshows.apps.TvshowsConfig',
    'channels.apps.ChannelsConfig',
    'movies.apps.MoviesConfig',
    'accounts.apps.AccountsConfig',
    'pages.apps.PagesConfig',
    #packgaes
    'jazzmin',
    'django_filters',
    'widget_tweaks',
    #system
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    #'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'movflex.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates') ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.template.context_processors.i18n',
                'django.contrib.messages.context_processors.messages',
                
            ],
        },
    },
]

WSGI_APPLICATION = 'movflex.wsgi.application'

TEMPLATE_CONTEXT_PROCESSORS = {
    "dajngo.core.context_processors.auth",
    "dajngo.core.context_processors.debug",
    "dajngo.core.context_processors.il8n",
    "dajngo.core.context_processors.media",
    "dajngo.core.context_processors.request",
}
# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'movflex_movies_tvshows_db',
        'USER': 'root',
        'PASSWORD': '',
        'HOST': '127.0.0.1',
        'PORT': '3306',
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'"
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

LANGUAGE_CODE = 'en'
LANGUAGES = [
    ('en' , ('English')),
    ('ar' , ('Arabic')),
    
]
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_ROOT = os.path.join(BASE_DIR , 'static' )
STATIC_URL = 'static/'

STATICFILES_DIRS =[
    os.path.join(BASE_DIR , 'movflex/static')
]
# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#media_folder 
MEDIA_ROOT = os.path.join(BASE_DIR , 'media' )
MEDIA_URL = 'media/'


#jazzmin_admin settings
JAZZMIN_SETTINGS ={
    "site_title":"Movflex Administration",
    "site_header":"Movflex",
    "site_brand":"Movflex",
    "site_logo":"images/logo-red.png",
    "login_logo":"images/logo-red.png",
    "login_logo_dark":"images/logo-red.png",
    "welcome_sign":"Welcome to Movflex Administration",
    "copyright":"A A M Programming",

    "icons":{
            "auth":"fas-users-cog",
            "auth.user":"fas fa-user",
            "auth.group":"fas fa-users",
            "accounts":"fas fa-users",
            "accounts.userprofile":"fas fa-address-card",
            "accounts.movie_notification":"fas fa-bell",
            "accounts.tvshow_notification":"fas fa-bell",
            "channels":"fas fa-podcast",
            "channels.channel":"fas fa-podcast",
            "cast_and_crew.cast":"fab fa-black-tie",
            "cast_and_crew.director":"fas fa-bullhorn",
            "cast_and_crew.writer":"fas fa-pen-nib",
            "pages.category":"fas fa-chart-pie",
            "pages.Language":"fa fa-language",
            "pages.Release_year":"fas fa-calendar-alt",
            "pages.tag":"fas fa-hashtag",
            "pages.sequrty_question":"fas fa-question-circle",
            "movies":"fas fa-film",
            "movies.movie":"fas fa-film",
            "movies.comment":"fas fa-comment",
            "tvshows.tvshow":"fas fa-tv",
            "tvshows.comment":"fas fa-comment",
        },

}
JAZZMIN_UI_TWEAKS ={
    #Lights
    #"theme":"cerulen",
    #"theme":"cosom",
    #"theme":"flatly",
    #"theme":"journal", #good
    #"theme":"litera", #good
    #"theme":"lumen",
    #"theme":"lux",
    "theme":"materia", #nice
    #"theme":"minty",
    #"theme":"pulse",
    #"theme":"sandston",
    #"theme":"simplex", #good
    #"theme":"scetchy",
    #"theme":"spacelab",
    #"theme":"united",
    #"theme":"yeti", #good


    #dark
    #"theme":"darkly",
    #"theme":"cyborg",
    #"theme":"slate",
    #"theme":"solar", #good
    #"theme":"superhero",

}