# Generated by Django 4.0.3 on 2023-01-31 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvshows', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user_history',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tvshow_favorits',
            field=models.ManyToManyField(related_name='tvshow_favorits', to='tvshows.tvshow'),
        ),
    ]
