# Generated by Django 4.0.3 on 2023-04-11 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_tag'),
        ('accounts', '0002_remove_userprofile_user_history_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='country',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='favorit_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pages.category'),
        ),
    ]
