# Generated by Django 4.0.3 on 2023-05-29 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userprofile_movie_history_userprofile_tvshow_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='securty_answer',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='securty_question',
            field=models.TextField(null=True),
        ),
    ]
