# Generated by Django 4.0.3 on 2023-05-29 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_sequrty_question'),
        ('accounts', '0006_userprofile_securty_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='securty_question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pages.sequrty_question'),
        ),
    ]
