# Generated by Django 4.0.3 on 2023-06-04 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tvshows', '0024_alter_tvshow_watch_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0030_movie_coming_soon'),
        ('accounts', '0013_remove_notification_movie_notification_movie_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notification',
            new_name='Movie_Notification',
        ),
        migrations.CreateModel(
            name='Tvshow_Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read', models.BooleanField(default=False)),
                ('tvshow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tvshows.tvshow')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
