# Generated by Django 4.0.3 on 2023-06-04 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_rename_notification_movie_notification_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie_notification',
            old_name='movie',
            new_name='show',
        ),
        migrations.RenameField(
            model_name='tvshow_notification',
            old_name='tvshow',
            new_name='show',
        ),
    ]
