# Generated by Django 4.0.3 on 2023-02-03 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tvshows', '0002_alter_tvshow_category_alter_tvshow_release_year'),
        ('movies', '0003_alter_movie_category_alter_movie_release_year'),
        ('cast_and_crew', '0002_release_year_director_job_writer_job'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Release_year',
        ),
    ]
