# Generated by Django 4.0.3 on 2023-05-14 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cast_and_crew', '0003_delete_category_delete_release_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='cast',
            name='age',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cast',
            name='country',
            field=models.CharField(default=1, max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='director',
            name='age',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='director',
            name='country',
            field=models.CharField(default=1, max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='writer',
            name='age',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='writer',
            name='country',
            field=models.CharField(default=1, max_length=80),
            preserve_default=False,
        ),
    ]
