# Generated by Django 4.0.3 on 2023-09-03 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cast_and_crew', '0004_cast_age_cast_country_director_age_director_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cast',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='director',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='writer',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
