# Generated by Django 4.0.3 on 2023-09-03 08:55

from django.db import migrations
from django.utils.text import slugify

def update_existing_objects(apps,schema_editor):

    Cast = apps.get_model('cast_and_crew','Cast')
    Director = apps.get_model('cast_and_crew','Director')
    Writer = apps.get_model('cast_and_crew','Writer')

    for cast in Cast.objects.all():
        cast.slug = slugify(cast.name)
        cast.save()

    for director in Director.objects.all():
        director.slug = slugify(director.name)
        director.save()

    for writer in Writer.objects.all():
        writer.slug = slugify(writer.name)
        writer.save()
class Migration(migrations.Migration):

    dependencies = [
        ('cast_and_crew', '0005_cast_slug_director_slug_writer_slug'),
    ]

    operations = [
        migrations.RunPython(update_existing_objects)
    ]
