# Generated by Django 4.0.3 on 2023-02-13 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
