# Generated by Django 4.0.3 on 2023-02-03 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
        ('movies', '0002_remove_movie_released_date_movie_download_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pages.category'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pages.release_year'),
        ),
    ]
