# Generated by Django 4.0.3 on 2023-02-12 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_release_year_options'),
        ('movies', '0006_tag_part'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='poster',
            field=models.ImageField(default=1, upload_to='photos/posters/movies_parts'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(upload_to='photos/posters/movies'),
        ),
        migrations.AlterField(
            model_name='part',
            name='release_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movies_parts', to='pages.release_year'),
        ),
    ]
