# Generated by Django 4.0.3 on 2023-02-12 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_part_poster_alter_movie_poster_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='download_url',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='video_url',
        ),
    ]
