# Generated by Django 4.0.3 on 2023-02-12 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_remove_movie_download_url_remove_movie_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='parts',
            field=models.ManyToManyField(to='movies.part'),
        ),
        migrations.AddField(
            model_name='movie',
            name='tags',
            field=models.ManyToManyField(to='movies.tag'),
        ),
    ]
