# Generated by Django 4.0.3 on 2023-02-13 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_movie_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='slug',
        ),
    ]
