# Generated by Django 4.0.3 on 2023-02-13 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_remove_movie_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='parts',
            field=models.ManyToManyField(null=True, to='movies.part'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='tags',
            field=models.ManyToManyField(null=True, to='movies.tag'),
        ),
    ]
