# Generated by Django 4.0.3 on 2023-02-13 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0014_alter_movie_parts_alter_movie_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='parts',
            field=models.ManyToManyField(blank=True, null=True, to='movies.part'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='movies.tag'),
        ),
    ]
