# Generated by Django 4.0.3 on 2023-02-13 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_tag'),
        ('movies', '0019_alter_part_options_remove_movie_tags_delete_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='movies_tags', to='pages.tag'),
        ),
    ]
