# Generated by Django 4.0.3 on 2023-02-14 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0020_movie_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='parts',
        ),
        migrations.DeleteModel(
            name='Part',
        ),
    ]
