# Generated by Django 4.0.3 on 2023-02-14 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0022_movie_watc_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='number_Of_seasons',
            new_name='season',
        ),
    ]
