# Generated by Django 4.0.3 on 2023-02-14 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0023_rename_number_of_seasons_movie_season'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='watc_url',
            new_name='watch_url',
        ),
    ]
