# Generated by Django 4.0.3 on 2023-02-26 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0024_rename_watc_url_movie_watch_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['release_year']},
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='number_votes',
            new_name='number_views',
        ),
    ]
