# Generated by Django 4.0.3 on 2023-06-03 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0029_alter_movie_watch_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='coming_soon',
            field=models.BooleanField(default=False),
        ),
    ]
