# Generated by Django 4.0.3 on 2023-09-03 14:52

from django.db import migrations
from django.utils.text import slugify

def update_existing_objects(apps,schema_editor):

    Movie = apps.get_model('movies','Movie')
    

    for movie in Movie.objects.all():
        movie.slug = slugify(movie.name + ' ' + str(movie.season) )
        movie.save()

class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0033_alter_movie_slug'),
    ]

    operations = [
        migrations.RunPython(update_existing_objects)
    ]
